"""empty message

Revision ID: 74167e224676
Revises: 990fcbeaa95f
Create Date: 2022-08-14 17:29:36.132365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74167e224676'
down_revision = '990fcbeaa95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
