"""empty message

Revision ID: a7bfc9662608
Revises: 1269804312a9
Create Date: 2022-08-08 09:07:01.578010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bfc9662608'
down_revision = '1269804312a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    # op.drop_column('Artist', 'lookingForTalent')
    op.add_column('Venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    # op.drop_column('Venue', 'lookingForTalent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('lookingForTalent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'looking_for_talent')
    op.add_column('Artist', sa.Column('lookingForTalent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'looking_for_talent')
    # ### end Alembic commands ###
